//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace emuPCE.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("emuPCE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string BackToMain {
            get {
                return ResourceManager.GetString("BackToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cheat codes 的本地化字符串。
        /// </summary>
        internal static string CheatCode {
            get {
                return ResourceManager.GetString("CheatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock speed (TAB) 的本地化字符串。
        /// </summary>
        internal static string FastSpeed {
            get {
                return ResourceManager.GetString("FastSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File(&amp;F)) 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arial 的本地化字符串。
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Address 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_btnadd_Click_新建 {
            get {
                return ResourceManager.GetString("Form_Cheat_btnadd_Click_新建", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Codes 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_Form_Cheat_的金手指 {
            get {
                return ResourceManager.GetString("Form_Cheat_Form_Cheat_的金手指", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetch Cheats Online 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_FetchCheatsOnline {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_FetchCheatsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_保存 {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 del 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_删除 {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Codes 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_地址代码 {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_地址代码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 add 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_增加 {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_增加", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_导入 {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_导入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_应用金手指 {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_应用金手指", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_读取 {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_读取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cheat Codes 的本地化字符串。
        /// </summary>
        internal static string Form_Cheat_InitializeComponent_金手指 {
            get {
                return ResourceManager.GetString("Form_Cheat_InitializeComponent_金手指", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Value 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_内存搜索 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_内存搜索", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Editor 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_内存编辑 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_内存编辑", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refrsh 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_刷新 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GO 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_前往地址 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_前往地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DWORD 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_双字DWORD {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_双字DWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_地址 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WORD 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_字WORD {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_字WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Byte 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_字节Byte {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_字节Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_搜索 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_搜索", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 Results 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_搜索到0个地址只显示前500个 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_搜索到0个地址只显示前500个", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value Type 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_搜索类型 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_搜索类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_数值 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_数值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_浮点Float {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_浮点Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Refrsh 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_自动刷新 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_自动刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_InitializeComponent_重置 {
            get {
                return ResourceManager.GetString("Form_Mem_InitializeComponent_重置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Results 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_updateml_个地址只显示前500个 {
            get {
                return ResourceManager.GetString("Form_Mem_updateml_个地址只显示前500个", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        internal static string Form_Mem_updateml_搜索到 {
            get {
                return ResourceManager.GetString("Form_Mem_updateml_搜索到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string Form_Set_Form_Set_set {
            get {
                return ResourceManager.GetString("Form_Set_Form_Set_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audiobuffer(ms) 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_audio {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable console 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_con {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame skip 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_fsk {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_fsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defaults 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_gbs {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_gbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep 4:3 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_Keep43 {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_Keep43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame limit 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_limit {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_save {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify only if known 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_不清楚作用的设置尽量不要修改 {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_不清楚作用的设置尽量不要修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IR Scale 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_内部分辨率放大 {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_内部分辨率放大", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adaptive 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_自适应 {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_自适应", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string Form_Set_InitializeComponent_设置 {
            get {
                return ResourceManager.GetString("Form_Set_InitializeComponent_设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame skip (D2D, D3D) 的本地化字符串。
        /// </summary>
        internal static string Frameskip {
            get {
                return ResourceManager.GetString("Frameskip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC-Engine emulator released under the MIT License 的本地化字符串。
        /// </summary>
        internal static string FrmAbout_InitializeComponent_read {
            get {
                return ResourceManager.GetString("FrmAbout_InitializeComponent_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub: 的本地化字符串。
        /// </summary>
        internal static string FrmAbout_InitializeComponent_read2 {
            get {
                return ResourceManager.GetString("FrmAbout_InitializeComponent_read2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string FrmAbout_InitializeComponent_关于 {
            get {
                return ResourceManager.GetString("FrmAbout_InitializeComponent_关于", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintainer 的本地化字符串。
        /// </summary>
        internal static string FrmAbout_InitializeComponent_维护者 {
            get {
                return ResourceManager.GetString("FrmAbout_InitializeComponent_维护者", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string FrmInput_InitializeComponent_保存设置 {
            get {
                return ResourceManager.GetString("FrmInput_InitializeComponent_保存设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press any key, ESC to cancel 的本地化字符串。
        /// </summary>
        internal static string FrmInput_InitializeComponent_按下 {
            get {
                return ResourceManager.GetString("FrmInput_InitializeComponent_按下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard Config 的本地化字符串。
        /// </summary>
        internal static string FrmInput_InitializeComponent_按键设置 {
            get {
                return ResourceManager.GetString("FrmInput_InitializeComponent_按键设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Screen (F2) 的本地化字符串。
        /// </summary>
        internal static string FrmMain_InitializeComponent_FullScreenF2 {
            get {
                return ResourceManager.GetString("FrmMain_InitializeComponent_FullScreenF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oops 的本地化字符串。
        /// </summary>
        internal static string FrmMain_LoadRom_nobios {
            get {
                return ResourceManager.GetString("FrmMain_LoadRom_nobios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State Saved 的本地化字符串。
        /// </summary>
        internal static string FrmMain_SaveState_saved {
            get {
                return ResourceManager.GetString("FrmMain_SaveState_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StateSlot 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Timer_Elapsed_存档槽 {
            get {
                return ResourceManager.GetString("FrmMain_Timer_Elapsed_存档槽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Joy First 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Timer_Elapsed_手柄优先 {
            get {
                return ResourceManager.GetString("FrmMain_Timer_Elapsed_手柄优先", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAUSE 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Timer_Elapsed_暂停中 {
            get {
                return ResourceManager.GetString("FrmMain_Timer_Elapsed_暂停中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key First 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Timer_Elapsed_键盘优先 {
            get {
                return ResourceManager.GetString("FrmMain_Timer_Elapsed_键盘优先", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key config 的本地化字符串。
        /// </summary>
        internal static string KeySet {
            get {
                return ResourceManager.GetString("KeySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Game 的本地化字符串。
        /// </summary>
        internal static string LoadDIsk {
            get {
                return ResourceManager.GetString("LoadDIsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load state (F6) 的本地化字符串。
        /// </summary>
        internal static string LoadState {
            get {
                return ResourceManager.GetString("LoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search memory 的本地化字符串。
        /// </summary>
        internal static string memedit {
            get {
                return ResourceManager.GetString("memedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause (speac) 的本地化字符串。
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render(&amp;R) 的本地化字符串。
        /// </summary>
        internal static string Render {
            get {
                return ResourceManager.GetString("Render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveState 的本地化字符串。
        /// </summary>
        internal static string RomList_DrawInfoBoxes_即时存档 {
            get {
                return ResourceManager.GetString("RomList_DrawInfoBoxes_即时存档", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last  Play 的本地化字符串。
        /// </summary>
        internal static string RomList_DrawInfoBoxes_最后运行 {
            get {
                return ResourceManager.GetString("RomList_DrawInfoBoxes_最后运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cheats 的本地化字符串。
        /// </summary>
        internal static string RomList_DrawInfoBoxes_金手指 {
            get {
                return ResourceManager.GetString("RomList_DrawInfoBoxes_金手指", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string RomList_RomList_修改设置 {
            get {
                return ResourceManager.GetString("RomList_RomList_修改设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string RomList_RomList_删除 {
            get {
                return ResourceManager.GetString("RomList_RomList_删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon from savedata 的本地化字符串。
        /// </summary>
        internal static string RomList_RomList_取存档图标 {
            get {
                return ResourceManager.GetString("RomList_RomList_取存档图标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memcard mange 的本地化字符串。
        /// </summary>
        internal static string RomList_RomList_存档管理 {
            get {
                return ResourceManager.GetString("RomList_RomList_存档管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cheat Codes 的本地化字符串。
        /// </summary>
        internal static string RomList_RomList_编辑金手指 {
            get {
                return ResourceManager.GetString("RomList_RomList_编辑金手指", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set icon 的本地化字符串。
        /// </summary>
        internal static string RomList_RomList_设置图标 {
            get {
                return ResourceManager.GetString("RomList_RomList_设置图标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search subdirectories? 的本地化字符串。
        /// </summary>
        internal static string RomList_SearchDir_是否要搜索子目录 {
            get {
                return ResourceManager.GetString("RomList_SearchDir_是否要搜索子目录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save state (F5) 的本地化字符串。
        /// </summary>
        internal static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Games 的本地化字符串。
        /// </summary>
        internal static string SearchDir {
            get {
                return ResourceManager.GetString("SearchDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo state load 的本地化字符串。
        /// </summary>
        internal static string UnLoad {
            get {
                return ResourceManager.GetString("UnLoad", resourceCulture);
            }
        }
    }
}
